### ISSUE TITLE
Level 40 Html builder can't run in Javascript(Canvas) configuration as stated in the task

### ISSUE THREAD

**Issue by KuSh** [Kotlin/kotlin-koans-edu-obsolete#7]
html.kt : Error:(1, 7) Unresolved reference: java

IIUC the ```import java.util.ArrayList``` in html.kt should be removed (as kotlin.collections.* is imported by default)

regards,
Nicolas

**Comment by mkraynov** [comment]
Fixed in #9. Issue could be closed, I think.
